### ISSUE TITLE
get_by_id_or_none

### ISSUE THREAD

**Issue by vitidev** [klen/peewee-aio#3]
Need this feature

Of course I can use

     await manager.get_or_none(Model, Model.id == id)

but for this I need to have `manager` in place

or something like `get_by_id(Model, pk, raise_non_exists=True)` because the name `get_by_id_or_none` is just awful

**Comment by klen** [comment]
The library follows API from `peewee` and only provides async support. Peewee has two similar methods: `get_or_none` and `get_by_id`. Both of the methods are supported by `AIOModel`. I don't think that we have to expand peewee interface more than needed.
