### ISSUE TITLE
Can't Connect PostgreSQL Database When Connection URIs Contains Special Characters

### ISSUE THREAD

**Issue by LeeWantfly** [klen/peewee-aio#6]
Hello, I had met a problem, it's failed when i was connecting my PostgreSQL database, 
i had read the pg documents, https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING,
Because my passwords contains special characters '@', i had to convert my passwords with `urllib.parse.quote_plus()` function, but it was still failed. By contrast, it was success when i connecting another PostgreSQL database without special charaters passwords。
Here is the code:
````
from peewee_aio import Manager
manager = Manager('postgresql://user:pass%40word123@myhost:5432/mydatabase')
.....
```
Traceback (most recent call last):
  File "D:\Miniconda3\envs\env_myproj\lib\asyncio\windows_events.py", line 457, in finish_recv
    return ov.getresult()
OSError:  [WinError 64] The network name specified is no longer available

**Comment by klen** [comment]
@LeeWantfly try to use password without encoding like 'postgresql://user:pass@word123@myhost:5432/mydatabase'
