### ISSUE TITLE
 Do not peewee-aio support ModelCompoundSelectQuery ?

### ISSUE THREAD

**Issue by LeeWantfly** [klen/peewee-aio#7]
it was failed when i joining many table and using with cte in peewee-aio.
Here is my code
```
with self._manager.allow_sync():
                async with self._manager.connection():
                    self._nrow = await self._query.count()
```
TypeError: object ModelCompoundSelectQuery can't be used in 'await' expression

**Comment by klen** [comment]
@LeeWantfly thank you for the report fixed in the latest version
