### ISSUE TITLE
Pycharm: Class Role must implement all abstract methods

### ISSUE THREAD

**Issue by vitidev** [klen/peewee-aio#9]
peewee-aio: 1.4.3
PyCharm: 2022.3.3
code from README.md

![Image 1](https://user-images.githubusercontent.com/2243958/227602437-759a7054-aab2-4e65-acd5-52c5dd5c666e.png)

and suggests "Add abc.ABC to superclass"
or implement methods "bulk_create" and "bulk_update"

**Comment by klen** [comment]
Thank you for the issue. Has been fixed in the latest (1.5.0) release.
